### ISSUE TITLE
MISRC Extract

### ISSUE THREAD

**Issue by harrypm** [Stefan-Olt/MISRC#3]
Currently while capture is universal self contained extraction tools only exist for Windows.

# Self Contained Builds

- [x] Windows Build
- [x] Linux App Image
- [x] MacOS App

**Comment by Stefan-Olt** [comment]
A appimage for Linux does not make any sense, because it's a command-line application, so you cannot run it like a AppImage and also it does not have any dependencies, that's what AppImages are designed for, include all dependencies. A simple binary would be more than enough. But Linux binaries are a bit tricky: You need to build them on a old machine with old libc6, because they won't run with newer libc6. But I don't think linux binaries are needed at all, because building it on Linux is really simple and the vast majority of Linux users know how to compile something.

I don't know how it's done, but I think GitHub can create Release builds. You need to setup somekind of VM, that get's started when you make a new release and it will build all Release artifacts. Not sure if that works for ARM Mac yet

**Comment by harrypm** [comment]
Automated appimage builds are possible for example the [tbc-video-export](https://github.com/JuniorIsAJitterbug/tbc-video-export/releases) tool is a CLI tool but now has exe & appimage builds automated on every commit to make a new build release hands off wise, this would be ideal to setup here as well, best to talk to Jitterbug on the discord about it.

Currently the extract tool has build issues on Mint 21.3 and outputs this:

```
CMake Error at CMakeLists.txt:7 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by Stefan-Olt** [comment]
The build issue is exactly what cmake reported, you do not have nasm installed, can be solved by: `sudo apt install nasm`
nasm is only needed for building misrc_extract, not for running (it is used to assemble the hand-written assembly).
I will talk to jitterbug how to make this github actions

**Comment by harrypm** [comment]
Yeah that fixed the build process, updated the wiki docs for it too.

**Comment by Stefan-Olt** [comment]
Thanks to Jitterbug there are now automated builds for Linux, Windows and macOS (Intel and ARM)
